import { Providers } from '@/redux/provider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Menu from '../layout/component/Menu'
import './globals.css'
import Sidebar from '@/layout/component/Sidebar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers><Menu />

          <div className='flex justify-between px-4 mx-auto max-w-8xl'>
            <div className='hidden mb-6 xl:block lg:w-80'>
              <Sidebar />
            </div>
            <div className='w-full mx-auto'>
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html >
  )
}
