import classnames from 'classnames'
import { Providers } from '@/redux/provider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Menu from '../layout/component/Menu'
import './globals.css'
import Sidebar from '@/layout/component/Sidebar'
const inter = Inter({ subsets: ['latin'] })
import { DarkThemeToggle, Flowbite } from '@flowbite';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Flowbite>
      <html lang="en">
        <body className={classnames(inter.className)}>
          <Providers>
            <Menu />
            <div className='container mx-auto'>
              {children}
            </div>
          </Providers>
        </body>
      </html >
    </Flowbite>
  )
}
// 1. 모달
// 2. alert
// 3. navi
// 4. highlight text
// 5. spinner
// 6. pagination
// 7. paper canvas
// 8. editor / quill
// 9. select

// 10. picker / Date, Time, Month, Time
// 11. calendar
// 12. Toolbar
// 13. Button
// 14. address